### ISSUE TITLE
Please add info which version are supported

### ISSUE THREAD

**Issue by mariobehling** [fossasia/loklak_wok_android#1]
Currently I cannot get it running under Android 2.x. It would be great, if people could just keep their old phones running with loklak wok.

**Comment by Orbiter** [comment]
The lowest android version is 4.0.3. I have a very old android phone (HTC Vision / Desire Z) from 2010 which I used successfully for testing loklak wok. Android 2.x and 3.x is too old for this kind of code.

**Comment by Orbiter** [comment]
I discovered the root cause that API 11 is the lowest possible version: the processing library dropped support for gingerbread devices in https://github.com/omerjerk/processing-android/commit/bbc5af9d8014596888cb56b63b18d086e2e0b920 
To support these devices again, we would have to patch the processing library.

However, this does not affect the scraper code for loklak. A clone of this app which droppes processing support can support API lower than 11

**Comment by Orbiter** [comment]
After some testing I can confirm that this app works also on Android 3.0 (honeycomb). Fixed project set-up accordingly https://github.com/loklak/loklak_wok_android/commit/083a070d3af6dae1548c75ea5ec9949c0ecaff73
